name: 'reminder'
on:
  issue_comment:
    types: [created, edited]

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
    - uses: agrc/reminder-action@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
