name: 'reminder'
on:
  issue_comment:
    types: [created, edited]

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
    - name: check for reminder
      uses: agrc/reminder-action@main
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.context.repository }}
        repository_owner: ${{ github.context.repository_owner }}
